/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Majus
 */
public class Practica2 extends javax.swing.JFrame {

    // Controlar stacks
    Stack<Double> stack = new Stack<Double>();
    double number;
    
    // Guardar Operaciones
    int countLogs = 0;
    int indexLog = 500;
    GuardarLog[] logs = new GuardarLog[indexLog];
    /**
     * Creates new form Practica2
     */
    public Practica2() {
        initComponents();
        
        this.setTitle("Calculadora");
        this.setDefaultCloseOperation(3);
        this.setSize(430,400);
        this.setMaximumSize(new Dimension(430,400));
        this.setMinimumSize(new Dimension(430,400));
        this.setLocationRelativeTo(null);
        this.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setMaximumSize(new java.awt.Dimension(430, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(430, 400));
        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(java.awt.Color.darkGray);
        jTextField1.setForeground(java.awt.Color.white);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(39, 20, 360, 25);

        jTextField2.setEditable(false);
        jTextField2.setBackground(java.awt.Color.darkGray);
        jTextField2.setForeground(java.awt.Color.white);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(40, 50, 360, 25);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(40, 80, 360, 25);

        jButton1.setText("4");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 180, 50, 50);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 130, 50, 50);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 130, 50, 50);

        jButton4.setText("5");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(90, 180, 50, 50);

        jButton5.setText("6");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(140, 180, 50, 50);

        jButton6.setText("7");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(40, 230, 50, 50);

        jButton7.setText("8");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(90, 230, 50, 50);

        jButton8.setText("9");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(140, 230, 50, 50);

        jButton9.setText("Enter");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(40, 330, 150, 50);

        jButton11.setText("0");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(90, 280, 50, 50);

        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(260, 180, 65, 50);

        jButton13.setText("1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(40, 130, 50, 50);

        jButton14.setText("/");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(260, 130, 65, 50);

        jButton15.setText("*");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(200, 130, 65, 50);

        jButton16.setText("cls");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(330, 280, 65, 50);

        jButton22.setText("+");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(200, 180, 65, 50);

        jButton17.setText("√");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(200, 230, 65, 50);

        jButton18.setText("x^2");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(200, 280, 65, 50);

        jButton19.setText("Sie(x)");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(330, 180, 65, 50);

        jButton20.setText("Cos(x)");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(330, 130, 65, 50);

        jButton10.setText("Tan(x)");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(330, 230, 65, 50);

        jButton21.setText("x√");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(260, 230, 65, 50);

        jButton23.setText("Log de datos");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(200, 330, 125, 50);

        jButton24.setText("+/-");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(40, 280, 50, 50);

        jButton25.setText(".");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(140, 280, 50, 50);

        jButton27.setText("x^y");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(260, 280, 65, 50);
        jButton27.getAccessibleContext().setAccessibleName("x y ");

        jButton26.setText("Del");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(330, 330, 65, 50);

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/images/back.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(430, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(430, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(430, 400));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // btn 1
        jTextField3.setText(jTextField3.getText() + "1");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // btn 2
        jTextField3.setText(jTextField3.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // btn Enter
        try{
            number = Double.parseDouble(jTextField3.getText().trim());
            jTextField1.setText(jTextField2.getText());
            jTextField2.setText(jTextField3.getText());
            stack.push(number);
            jTextField3.setText("");
            
            logs[countLogs] = new GuardarLog(String.valueOf(number),"Push", Arrays.toString(stack.toArray()) );
            countLogs++;
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Usted no ingreso un numero! Intentelo de nuevo", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // btn3
        jTextField3.setText(jTextField3.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // btn 4
        jTextField3.setText(jTextField3.getText() + "4");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // btn 5
        jTextField3.setText(jTextField3.getText() + "5");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // btn 6
        jTextField3.setText(jTextField3.getText() + "6");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // btn 7
        jTextField3.setText(jTextField3.getText() + "7");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // btn 8
        jTextField3.setText(jTextField3.getText() + "8");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // btn 9
        jTextField3.setText(jTextField3.getText() + "9");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // btn 0
        jTextField3.setText(jTextField3.getText() + "0");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // cls btn
        
        // vaciar stack
        while(!stack.isEmpty()){
            stack.pop();
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // Suma
        double num1 = 0;
        double num2 = 0;
        if(stack.size() >= 2){
            num1 = stack.pop();
            num2 = stack.pop();
            stack.push(num1+num2);
            logs[countLogs] = new GuardarLog("+","Sumar", Arrays.toString(stack.toArray()) );
            countLogs++;
            jTextField3.setText(String.valueOf(num1+num2));
        }
        
        System.out.println("num1: " + num1);
        System.out.println("num2: " + num2);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Resta
        double num1 = 0;
        double num2 = 0;
        if(stack.size() >= 2){
            num1 = stack.pop();
            num2 = stack.pop();
            stack.push(num2-num1);
            logs[countLogs] = new GuardarLog("-","Restar", Arrays.toString(stack.toArray()) );
            countLogs++;
            jTextField3.setText(String.valueOf(num2 - num1));
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // Division
        double num1 = 0;
        double num2 = 0;
        if(stack.size() >= 2){
            num1 = stack.pop();
            num2 = stack.pop();
            stack.push(num2/num1);
            logs[countLogs] = new GuardarLog("/","Dividir", Arrays.toString(stack.toArray()) );
            countLogs++;
            jTextField3.setText(String.valueOf(num2/num1));
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // Multiplicacion
        double num1 = 0;
        double num2 = 0;
        if(stack.size() >= 2){
            num1 = stack.pop();
            num2 = stack.pop();
            stack.push(num1*num2);
            logs[countLogs] = new GuardarLog("*","Multiplicar", Arrays.toString(stack.toArray()) );
            countLogs++;
            jTextField3.setText(String.valueOf(num2*num1));
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // Square root
        double num1 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            
            if(num1 < 0){
                num1 = num1*(-1);
                stack.push(Math.sqrt(num1));
                logs[countLogs] = new GuardarLog("√","Raiz cuadrada imaginaria", Arrays.toString(stack.toArray()) );
                countLogs++;
                jTextField3.setText(String.valueOf(Math.sqrt(num1)) + " i ");
            }else{
                stack.push(Math.sqrt(num1));
                logs[countLogs] = new GuardarLog("√","Raiz cuadrada", Arrays.toString(stack.toArray()) );
                countLogs++;
                jTextField3.setText(String.valueOf(Math.sqrt(num1)));
            }
            
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // Square btn
        double num1 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            stack.push(num1*num1);
                logs[countLogs] = new GuardarLog("x^2","n al cuadrado", Arrays.toString(stack.toArray()) );
                countLogs++;
            jTextField3.setText(String.valueOf(num1*num1));
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // Sine fctn
        double num1 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            stack.push(Math.sin(num1));
                logs[countLogs] = new GuardarLog("sen(x)","seno de x", Arrays.toString(stack.toArray()) );
                countLogs++;
            jTextField3.setText(String.valueOf(Math.sin(num1)));
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // Cosine fctn
        double num1 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            stack.push(Math.cos(num1));
                logs[countLogs] = new GuardarLog("cos(x)","coseno de x", Arrays.toString(stack.toArray()) );
                countLogs++;
            jTextField3.setText(String.valueOf(Math.cos(num1)));
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Tangent fctn
        double num1 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            stack.push(Math.tan(num1));
                logs[countLogs] = new GuardarLog("Tan(x)","Tangente de x", Arrays.toString(stack.toArray()) );
                countLogs++;
            jTextField3.setText(String.valueOf(Math.tan(num1)));
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // nth Root
        double num1 = 0;
        double num2 = 0;
        double total = 0;
        
        if (stack.size() >= 2) {
            num1 = stack.pop();
            num2 = stack.pop();
            
            if (num2 < 0 && num1%2 == 0) {
                num2 = num2 * (-1);
                total = Math.pow(Math.E, Math.log(num2) / num1);
                stack.push(total);
                logs[countLogs] = new GuardarLog("x√","Raiz n imaginaria", Arrays.toString(stack.toArray()) );
                countLogs++;
                jTextField3.setText(String.valueOf(total) +  " i ");
            } else {
                total = Math.pow(Math.E, Math.log(num2) / num1);
                stack.push(total);
                logs[countLogs] = new GuardarLog("x√","Raiz n", Arrays.toString(stack.toArray()) );
                countLogs++;
                jTextField3.setText(String.valueOf(total));
            }
        }

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // Log de datos
        
        Log logOperaciones = new Log(this);
        this.setVisible(false);
        logOperaciones.setVisible(true);
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // x power y
        
        double num1 = 0;
        double num2 = 0;
        if(stack.size() >= 1){
            num1 = stack.pop();
            num2 = stack.pop();
            stack.push(Math.pow(num2, num1));
                logs[countLogs] = new GuardarLog("x^y","n al y", Arrays.toString(stack.toArray()) );
                countLogs++;
            jTextField3.setText(String.valueOf(Math.pow(num2, num1)));
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // DEL btn
        try{
            jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-1));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No hay nada que borrar!!!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // Cambio de signo
        try{
            jTextField3.setText(String.valueOf(-1*Double.parseDouble(jTextField3.getText().trim())));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se puede cambiar el signo,Ingrese un nuermo primero","Info",JOptionPane.INFORMATION_MESSAGE );
        }
        
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // Punto
        jTextField3.setText(jTextField3.getText()+".");
    }//GEN-LAST:event_jButton25ActionPerformed

    
    //Metodo para guardar los datos en 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
